name: Development Branch Pull Request Workflow
on:
    pull_request: 
        branches: 
            - develop
            - feature/*
jobs:
    terraform-plan:
        uses: ./.github/workflows/terraform-plan.yml
        with:
            environment: development