name: "Terraform Plan"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TERRAFORM_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_CLOUD_WORKSPACE: "${{ vars.TERRAFORM_WORKSPACE_PREFIX }}-${{ inputs.environment }}"
  CONFIG_DIRECTORY: ./iac/terraform
